# Generated by Django 5.1.4 on 2025-01-30 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='top_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.product'),
        ),
    ]
