# Generated by Django 5.1.4 on 2025-02-03 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
